/*
 * Copyright (c) 2016. Codetector (Yaotian Feng)
 */

export const AUTHENTICATION = 'AUTHENTICATION'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const AUTHENTICATION_VERIFICATION_SUCCESS = 'AUTHENTICATION_VERIFICATION_SUCCESS'
export const AUTHENTICATION_REQUIRE_MFA = 'AUTHENTICATION_REQUIRE_MFA'
export const AUTHENTICATION_MFA_PASS = 'AUTHENTICATION_MFA_PASS'
export const AUTHENTICATION_MFA_ERROR = 'AUTHENTICATION_MFA_ERROR'
export const AUTHENTICATION_PERMISSIONS_CHANGE = 'AUTHENTICATION_PERMISSIONS_CHANGE'

export const USERINFO_EMAIL_CHANGE = 'USERINFO_EMAIL_CHANGE'
export const USERINFO_NAME_CHANGE = 'USERINFO_NAME_CHANGE'
export const USERINFO_PHONE_CHANGE = 'USERINFO_PHONE_CHANGE'
export const USERINFO_ID_CHANGE = 'USERINFO_ID_CHANGE'
export const USERINFO_LOGIN_HISTORY_CHANGE = 'USERINFO_LOGIN_HISTORY_CHANGE'
export const USERINFO_USER_MFA_STATUS_CHANGE = 'USERINFO_USER_MFA_STATUS_CHANGE'

export const SHOW_LOADING_SPINNER = 'SHOW_LOADING_SPINNER'
export const HIDE_LOADING_SPINNER = 'HIDE_LOADING_SPINNER'
