/*
 * Copyright (c) 2016. Codetector (Yaotian Feng)
 */

export const AUTHENTICATION = 'AUTHENTICATION'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const AUTHENTICATION_VERIFICATION_SUCCESS = 'AUTHENTICATION_VERIFICATION_SUCCESS'

export const USERINFO_USERNAME_CHANGE = 'USERINFO_USERNAME_CHANGE'
export const USERINFO_NAME_CHANGE = 'USERINFO_NAME_CHANGE'
